// Code generated by SQLBoiler 4.17.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"strconv"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/strmangle"
)

// M type is for providing columns and column values to UpdateAll.
type M map[string]interface{}

// ErrSyncFail occurs during insert when the record could not be retrieved in
// order to populate default value information. This usually happens when LastInsertId
// fails or there was a primary key configuration that was not resolvable.
var ErrSyncFail = errors.New("model: failed to synchronize data after insert")

type insertCache struct {
	query        string
	retQuery     string
	valueMapping []uint64
	retMapping   []uint64
}

type updateCache struct {
	query        string
	valueMapping []uint64
}

func makeCacheKey(cols boil.Columns, nzDefaults []string) string {
	buf := strmangle.GetBuffer()

	buf.WriteString(strconv.Itoa(cols.Kind))
	for _, w := range cols.Cols {
		buf.WriteString(w)
	}

	if len(nzDefaults) != 0 {
		buf.WriteByte('.')
	}
	for _, nz := range nzDefaults {
		buf.WriteString(nz)
	}

	str := buf.String()
	strmangle.PutBuffer(buf)
	return str
}

type TransportsTransportType string

// Enum values for TransportsTransportType
const (
	TransportsTransportTypePlane TransportsTransportType = "plane"
	TransportsTransportTypeTrain TransportsTransportType = "train"
	TransportsTransportTypeShip  TransportsTransportType = "ship"
	TransportsTransportTypeBus   TransportsTransportType = "bus"
)

func AllTransportsTransportType() []TransportsTransportType {
	return []TransportsTransportType{
		TransportsTransportTypePlane,
		TransportsTransportTypeTrain,
		TransportsTransportTypeShip,
		TransportsTransportTypeBus,
	}
}

func (e TransportsTransportType) IsValid() error {
	switch e {
	case TransportsTransportTypePlane, TransportsTransportTypeTrain, TransportsTransportTypeShip, TransportsTransportTypeBus:
		return nil
	default:
		return errors.New("enum is not valid")
	}
}

func (e TransportsTransportType) String() string {
	return string(e)
}

func (e TransportsTransportType) Ordinal() int {
	switch e {
	case TransportsTransportTypePlane:
		return 0
	case TransportsTransportTypeTrain:
		return 1
	case TransportsTransportTypeShip:
		return 2
	case TransportsTransportTypeBus:
		return 3

	default:
		panic(errors.New("enum is not valid"))
	}
}
