openapi: 3.0.2
info:
  title: "API"
  version: "2.0.0"
servers:
  - url: "http://localhost:8080"
    description: "Development server"
  - url: "http://localhost:3000"
    description: "Testing server"
security:
  - Bearer: []
tags:
  - name: "user"
    description: "Operations about user"
paths:
  /signUp:
    post:
      tags:
        - user
      summary: "Sign up a new user"
      description: "Allows a new user to sign up using their email and password."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignUpRequest"
            example:
              email: "new@ex.com"
              password: "password"
      responses:
        "200":
          description: "Successful sign up"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignUpResponse"
              example:
                message: "User successfully signed up"
                user:
                  id: 12345
                e mail: "newuser@example.com"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"

components:
  schemas:
    SignUpRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          description: "User's email"
          example: "newuser@example.com"
        password:
          type: string
          description: "User's password"
          example: "securepassword"
      required:
        - email
        - password
    SignUpResponse:
      type: object
      properties:
        message:
          type: string
          description: "A success message"
        user:
          type: object
          properties:
            id:
              type: integer
              format: int64
              description: "Newly created user's unique identifier"
            email:
              type: string
              description: "Email of the newly signed up user"
  responses:
    BadRequest:
      description: "Bad request"
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                description: "Error message"
          example:
            message: "Invalid request payload"

    InternalServerError:
      description: "Internal server error"
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                description: "Error message"
          example:
            message: "Internal server error"
